version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 99
  reviewers:
  - diogopms
  ignore:
  - dependency-name: alpine
    versions:
    - 3.13.3
    - 3.13.4
